FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV MODEL_PATH=/app/models/churn_model.pkl
EXPOSE 8000
CMD ["uvicorn", "api_churn:app", "--host", "0.0.0.0", "--port", "8000"]
